// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/getSmsCode.proto

package getSmsCode

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for GetSmsCode service

func NewGetSmsCodeEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for GetSmsCode service

type GetSmsCodeService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (GetSmsCode_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (GetSmsCode_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (GetSmsCode_BidiStreamService, error)
}

type getSmsCodeService struct {
	c    client.Client
	name string
}

func NewGetSmsCodeService(name string, c client.Client) GetSmsCodeService {
	return &getSmsCodeService{
		c:    c,
		name: name,
	}
}

func (c *getSmsCodeService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "GetSmsCode.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getSmsCodeService) ClientStream(ctx context.Context, opts ...client.CallOption) (GetSmsCode_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "GetSmsCode.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &getSmsCodeServiceClientStream{stream}, nil
}

type GetSmsCode_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type getSmsCodeServiceClientStream struct {
	stream client.Stream
}

func (x *getSmsCodeServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *getSmsCodeServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *getSmsCodeServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getSmsCodeServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getSmsCodeServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getSmsCodeServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *getSmsCodeService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (GetSmsCode_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "GetSmsCode.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &getSmsCodeServiceServerStream{stream}, nil
}

type GetSmsCode_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type getSmsCodeServiceServerStream struct {
	stream client.Stream
}

func (x *getSmsCodeServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *getSmsCodeServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *getSmsCodeServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getSmsCodeServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getSmsCodeServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getSmsCodeServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *getSmsCodeService) BidiStream(ctx context.Context, opts ...client.CallOption) (GetSmsCode_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "GetSmsCode.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &getSmsCodeServiceBidiStream{stream}, nil
}

type GetSmsCode_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type getSmsCodeServiceBidiStream struct {
	stream client.Stream
}

func (x *getSmsCodeServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *getSmsCodeServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *getSmsCodeServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getSmsCodeServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getSmsCodeServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getSmsCodeServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *getSmsCodeServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GetSmsCode service

type GetSmsCodeHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, GetSmsCode_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, GetSmsCode_ServerStreamStream) error
	BidiStream(context.Context, GetSmsCode_BidiStreamStream) error
}

func RegisterGetSmsCodeHandler(s server.Server, hdlr GetSmsCodeHandler, opts ...server.HandlerOption) error {
	type getSmsCode interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type GetSmsCode struct {
		getSmsCode
	}
	h := &getSmsCodeHandler{hdlr}
	return s.Handle(s.NewHandler(&GetSmsCode{h}, opts...))
}

type getSmsCodeHandler struct {
	GetSmsCodeHandler
}

func (h *getSmsCodeHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.GetSmsCodeHandler.Call(ctx, in, out)
}

func (h *getSmsCodeHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.GetSmsCodeHandler.ClientStream(ctx, &getSmsCodeClientStreamStream{stream})
}

type GetSmsCode_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type getSmsCodeClientStreamStream struct {
	stream server.Stream
}

func (x *getSmsCodeClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *getSmsCodeClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getSmsCodeClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getSmsCodeClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getSmsCodeClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *getSmsCodeHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.GetSmsCodeHandler.ServerStream(ctx, m, &getSmsCodeServerStreamStream{stream})
}

type GetSmsCode_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type getSmsCodeServerStreamStream struct {
	stream server.Stream
}

func (x *getSmsCodeServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *getSmsCodeServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getSmsCodeServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getSmsCodeServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getSmsCodeServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *getSmsCodeHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.GetSmsCodeHandler.BidiStream(ctx, &getSmsCodeBidiStreamStream{stream})
}

type GetSmsCode_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type getSmsCodeBidiStreamStream struct {
	stream server.Stream
}

func (x *getSmsCodeBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *getSmsCodeBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getSmsCodeBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getSmsCodeBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getSmsCodeBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *getSmsCodeBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
