// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/getImageCode.proto

package getImageCode

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for GetImageCode service

func NewGetImageCodeEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for GetImageCode service

type GetImageCodeService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (GetImageCode_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (GetImageCode_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (GetImageCode_BidiStreamService, error)
}

type getImageCodeService struct {
	c    client.Client
	name string
}

func NewGetImageCodeService(name string, c client.Client) GetImageCodeService {
	return &getImageCodeService{
		c:    c,
		name: name,
	}
}

func (c *getImageCodeService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "GetImageCode.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getImageCodeService) ClientStream(ctx context.Context, opts ...client.CallOption) (GetImageCode_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "GetImageCode.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &getImageCodeServiceClientStream{stream}, nil
}

type GetImageCode_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type getImageCodeServiceClientStream struct {
	stream client.Stream
}

func (x *getImageCodeServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *getImageCodeServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *getImageCodeServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getImageCodeServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getImageCodeServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getImageCodeServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *getImageCodeService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (GetImageCode_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "GetImageCode.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &getImageCodeServiceServerStream{stream}, nil
}

type GetImageCode_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type getImageCodeServiceServerStream struct {
	stream client.Stream
}

func (x *getImageCodeServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *getImageCodeServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *getImageCodeServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getImageCodeServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getImageCodeServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getImageCodeServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *getImageCodeService) BidiStream(ctx context.Context, opts ...client.CallOption) (GetImageCode_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "GetImageCode.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &getImageCodeServiceBidiStream{stream}, nil
}

type GetImageCode_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type getImageCodeServiceBidiStream struct {
	stream client.Stream
}

func (x *getImageCodeServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *getImageCodeServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *getImageCodeServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getImageCodeServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getImageCodeServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getImageCodeServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *getImageCodeServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GetImageCode service

type GetImageCodeHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, GetImageCode_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, GetImageCode_ServerStreamStream) error
	BidiStream(context.Context, GetImageCode_BidiStreamStream) error
}

func RegisterGetImageCodeHandler(s server.Server, hdlr GetImageCodeHandler, opts ...server.HandlerOption) error {
	type getImageCode interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type GetImageCode struct {
		getImageCode
	}
	h := &getImageCodeHandler{hdlr}
	return s.Handle(s.NewHandler(&GetImageCode{h}, opts...))
}

type getImageCodeHandler struct {
	GetImageCodeHandler
}

func (h *getImageCodeHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.GetImageCodeHandler.Call(ctx, in, out)
}

func (h *getImageCodeHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.GetImageCodeHandler.ClientStream(ctx, &getImageCodeClientStreamStream{stream})
}

type GetImageCode_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type getImageCodeClientStreamStream struct {
	stream server.Stream
}

func (x *getImageCodeClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *getImageCodeClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getImageCodeClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getImageCodeClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getImageCodeClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *getImageCodeHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.GetImageCodeHandler.ServerStream(ctx, m, &getImageCodeServerStreamStream{stream})
}

type GetImageCode_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type getImageCodeServerStreamStream struct {
	stream server.Stream
}

func (x *getImageCodeServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *getImageCodeServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getImageCodeServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getImageCodeServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getImageCodeServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *getImageCodeHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.GetImageCodeHandler.BidiStream(ctx, &getImageCodeBidiStreamStream{stream})
}

type GetImageCode_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type getImageCodeBidiStreamStream struct {
	stream server.Stream
}

func (x *getImageCodeBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *getImageCodeBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getImageCodeBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getImageCodeBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getImageCodeBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *getImageCodeBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
