# 应用名称
appname = "mainproject"
# 地址
httpaddr = "127.0.0.1"
# 端口
httpport = "8080"
# 数据库地址
mysqladdr = "127.0.0.1"
# 数据库端口
mysqlport = "3306"
# redis地址
redisaddr = "127.0.0.1"
# redis端口
redisport = "6379"
#fastdfs地址
fastdfsaddr = "127.0.0.1"
#fastdfs端口
fastdfsport = "3666"