// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/getUserInfo.proto

package getUserInfo

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for GetUserInfo service

func NewGetUserInfoEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for GetUserInfo service

type GetUserInfoService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (GetUserInfo_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (GetUserInfo_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (GetUserInfo_BidiStreamService, error)
}

type getUserInfoService struct {
	c    client.Client
	name string
}

func NewGetUserInfoService(name string, c client.Client) GetUserInfoService {
	return &getUserInfoService{
		c:    c,
		name: name,
	}
}

func (c *getUserInfoService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "GetUserInfo.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getUserInfoService) ClientStream(ctx context.Context, opts ...client.CallOption) (GetUserInfo_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "GetUserInfo.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &getUserInfoServiceClientStream{stream}, nil
}

type GetUserInfo_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type getUserInfoServiceClientStream struct {
	stream client.Stream
}

func (x *getUserInfoServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *getUserInfoServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *getUserInfoServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getUserInfoServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getUserInfoServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getUserInfoServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *getUserInfoService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (GetUserInfo_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "GetUserInfo.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &getUserInfoServiceServerStream{stream}, nil
}

type GetUserInfo_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type getUserInfoServiceServerStream struct {
	stream client.Stream
}

func (x *getUserInfoServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *getUserInfoServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *getUserInfoServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getUserInfoServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getUserInfoServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getUserInfoServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *getUserInfoService) BidiStream(ctx context.Context, opts ...client.CallOption) (GetUserInfo_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "GetUserInfo.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &getUserInfoServiceBidiStream{stream}, nil
}

type GetUserInfo_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type getUserInfoServiceBidiStream struct {
	stream client.Stream
}

func (x *getUserInfoServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *getUserInfoServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *getUserInfoServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getUserInfoServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getUserInfoServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getUserInfoServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *getUserInfoServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GetUserInfo service

type GetUserInfoHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, GetUserInfo_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, GetUserInfo_ServerStreamStream) error
	BidiStream(context.Context, GetUserInfo_BidiStreamStream) error
}

func RegisterGetUserInfoHandler(s server.Server, hdlr GetUserInfoHandler, opts ...server.HandlerOption) error {
	type getUserInfo interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type GetUserInfo struct {
		getUserInfo
	}
	h := &getUserInfoHandler{hdlr}
	return s.Handle(s.NewHandler(&GetUserInfo{h}, opts...))
}

type getUserInfoHandler struct {
	GetUserInfoHandler
}

func (h *getUserInfoHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.GetUserInfoHandler.Call(ctx, in, out)
}

func (h *getUserInfoHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.GetUserInfoHandler.ClientStream(ctx, &getUserInfoClientStreamStream{stream})
}

type GetUserInfo_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type getUserInfoClientStreamStream struct {
	stream server.Stream
}

func (x *getUserInfoClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *getUserInfoClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getUserInfoClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getUserInfoClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getUserInfoClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *getUserInfoHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.GetUserInfoHandler.ServerStream(ctx, m, &getUserInfoServerStreamStream{stream})
}

type GetUserInfo_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type getUserInfoServerStreamStream struct {
	stream server.Stream
}

func (x *getUserInfoServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *getUserInfoServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getUserInfoServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getUserInfoServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getUserInfoServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *getUserInfoHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.GetUserInfoHandler.BidiStream(ctx, &getUserInfoBidiStreamStream{stream})
}

type GetUserInfo_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type getUserInfoBidiStreamStream struct {
	stream server.Stream
}

func (x *getUserInfoBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *getUserInfoBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getUserInfoBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getUserInfoBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getUserInfoBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *getUserInfoBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
