// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/putUserName.proto

package putUserName

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PutUserName service

func NewPutUserNameEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for PutUserName service

type PutUserNameService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (PutUserName_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (PutUserName_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (PutUserName_BidiStreamService, error)
}

type putUserNameService struct {
	c    client.Client
	name string
}

func NewPutUserNameService(name string, c client.Client) PutUserNameService {
	return &putUserNameService{
		c:    c,
		name: name,
	}
}

func (c *putUserNameService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "PutUserName.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *putUserNameService) ClientStream(ctx context.Context, opts ...client.CallOption) (PutUserName_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "PutUserName.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &putUserNameServiceClientStream{stream}, nil
}

type PutUserName_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type putUserNameServiceClientStream struct {
	stream client.Stream
}

func (x *putUserNameServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *putUserNameServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *putUserNameServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *putUserNameServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *putUserNameServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *putUserNameServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *putUserNameService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (PutUserName_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "PutUserName.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &putUserNameServiceServerStream{stream}, nil
}

type PutUserName_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type putUserNameServiceServerStream struct {
	stream client.Stream
}

func (x *putUserNameServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *putUserNameServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *putUserNameServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *putUserNameServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *putUserNameServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *putUserNameServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *putUserNameService) BidiStream(ctx context.Context, opts ...client.CallOption) (PutUserName_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "PutUserName.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &putUserNameServiceBidiStream{stream}, nil
}

type PutUserName_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type putUserNameServiceBidiStream struct {
	stream client.Stream
}

func (x *putUserNameServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *putUserNameServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *putUserNameServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *putUserNameServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *putUserNameServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *putUserNameServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *putUserNameServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for PutUserName service

type PutUserNameHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, PutUserName_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, PutUserName_ServerStreamStream) error
	BidiStream(context.Context, PutUserName_BidiStreamStream) error
}

func RegisterPutUserNameHandler(s server.Server, hdlr PutUserNameHandler, opts ...server.HandlerOption) error {
	type putUserName interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type PutUserName struct {
		putUserName
	}
	h := &putUserNameHandler{hdlr}
	return s.Handle(s.NewHandler(&PutUserName{h}, opts...))
}

type putUserNameHandler struct {
	PutUserNameHandler
}

func (h *putUserNameHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.PutUserNameHandler.Call(ctx, in, out)
}

func (h *putUserNameHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.PutUserNameHandler.ClientStream(ctx, &putUserNameClientStreamStream{stream})
}

type PutUserName_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type putUserNameClientStreamStream struct {
	stream server.Stream
}

func (x *putUserNameClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *putUserNameClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *putUserNameClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *putUserNameClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *putUserNameClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *putUserNameHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.PutUserNameHandler.ServerStream(ctx, m, &putUserNameServerStreamStream{stream})
}

type PutUserName_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type putUserNameServerStreamStream struct {
	stream server.Stream
}

func (x *putUserNameServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *putUserNameServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *putUserNameServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *putUserNameServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *putUserNameServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *putUserNameHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.PutUserNameHandler.BidiStream(ctx, &putUserNameBidiStreamStream{stream})
}

type PutUserName_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type putUserNameBidiStreamStream struct {
	stream server.Stream
}

func (x *putUserNameBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *putUserNameBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *putUserNameBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *putUserNameBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *putUserNameBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *putUserNameBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
