// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/postRet.proto

package postRet

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PostRet service

func NewPostRetEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for PostRet service

type PostRetService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (PostRet_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (PostRet_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (PostRet_BidiStreamService, error)
}

type postRetService struct {
	c    client.Client
	name string
}

func NewPostRetService(name string, c client.Client) PostRetService {
	return &postRetService{
		c:    c,
		name: name,
	}
}

func (c *postRetService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "PostRet.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postRetService) ClientStream(ctx context.Context, opts ...client.CallOption) (PostRet_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "PostRet.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &postRetServiceClientStream{stream}, nil
}

type PostRet_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type postRetServiceClientStream struct {
	stream client.Stream
}

func (x *postRetServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *postRetServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *postRetServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *postRetServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postRetServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postRetServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *postRetService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (PostRet_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "PostRet.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &postRetServiceServerStream{stream}, nil
}

type PostRet_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type postRetServiceServerStream struct {
	stream client.Stream
}

func (x *postRetServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *postRetServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *postRetServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *postRetServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postRetServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postRetServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *postRetService) BidiStream(ctx context.Context, opts ...client.CallOption) (PostRet_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "PostRet.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &postRetServiceBidiStream{stream}, nil
}

type PostRet_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type postRetServiceBidiStream struct {
	stream client.Stream
}

func (x *postRetServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *postRetServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *postRetServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *postRetServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postRetServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postRetServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *postRetServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for PostRet service

type PostRetHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, PostRet_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, PostRet_ServerStreamStream) error
	BidiStream(context.Context, PostRet_BidiStreamStream) error
}

func RegisterPostRetHandler(s server.Server, hdlr PostRetHandler, opts ...server.HandlerOption) error {
	type postRet interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type PostRet struct {
		postRet
	}
	h := &postRetHandler{hdlr}
	return s.Handle(s.NewHandler(&PostRet{h}, opts...))
}

type postRetHandler struct {
	PostRetHandler
}

func (h *postRetHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.PostRetHandler.Call(ctx, in, out)
}

func (h *postRetHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.PostRetHandler.ClientStream(ctx, &postRetClientStreamStream{stream})
}

type PostRet_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type postRetClientStreamStream struct {
	stream server.Stream
}

func (x *postRetClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *postRetClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *postRetClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postRetClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postRetClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *postRetHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.PostRetHandler.ServerStream(ctx, m, &postRetServerStreamStream{stream})
}

type PostRet_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type postRetServerStreamStream struct {
	stream server.Stream
}

func (x *postRetServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *postRetServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *postRetServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postRetServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postRetServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *postRetHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.PostRetHandler.BidiStream(ctx, &postRetBidiStreamStream{stream})
}

type PostRet_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type postRetBidiStreamStream struct {
	stream server.Stream
}

func (x *postRetBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *postRetBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *postRetBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postRetBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postRetBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *postRetBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
